var imagemap={cacheData:{},currentPage:1,lastPage:"?",init:function(){this.get(this.process)},get:function(a){var d=this,c;1===this.currentPage?c="":c="?page="+this.currentPage;c="http://images.endoftheinter.net/imagemap.php"+c;"https:"==window.location.protocol&&(c=c.replace("http","https"));var b=new XMLHttpRequest;b.open("GET",c,!0);b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var c=document.createElement("html");c.innerHTML=b.responseText;a.call(d,c)}};b.send()},process:function(a){var d=
this.scrape(a);a=a.getElementsByClassName("infobar")[1].getElementsByTagName("a");this.lastPage=a[a.length-1].innerHTML;this.createPopup.call(this,d);this.iterateOverImages(d)},scrape:function(a){var d=a.getElementsByClassName("image_grid")[0];this.restore(function(a){for(var b=d.getElementsByTagName("img"),c=0,e=b.length;c<e;c++){var k=b[c],m=k.src;a.imagemap&&a.imagemap[m]&&(k.setAttribute("oldsrc",k.src),k.src=a.imagemap[m].data)}});a=d.getElementsByClassName("block_desc");for(var c=d.getElementsByClassName("grid_block"),
b=0,e=a.length;b<e;b++)a[b].style.display="none";b=0;for(e=c.length;b<e;b++)c[b].title="Click here to copy image code to clipboard";return d},createPopup:function(a,d){var c=this,b=document.createElement("div"),e=window.innerWidth,f=window.innerHeight,h=document.getElementsByClassName("body")[0];b.id="map_div";b.style.position="fixed";b.style.width=.95*e+"px";b.style.height=.95*f/2+"px";b.style.left=e-.975*e+"px";b.style.top=f-.975*f+"px";b.style.boxShadow="5px 5px 7px black";b.style.borderRadius=
"6px";b.style.opacity=1;b.style.backgroundColor="white";b.style.overFlow="scroll";if(d){var g=document.createElement("div"),l=document.createTextNode('Displaying results for query "'+query+'" :');g.appendChild(l);g.style.color="black";g.style.position="relative";g.style.left="15px";g.style.right="15px";g.style.top="15px";g.style.cssFloat="left";g.style.textAlign="left";g.style.width="100%";g.style.fontSize="16px";b.appendChild(g);a.style.maxHeight=.95*f/2-51+"px";a.style.maxWidth=.95*e-21+"px"}else a.style.maxWidth=
.95*e-6+"px",a.style.maxHeight=.95*f/2-6+"px";a.style.position="relative";a.style.top="5px";a.style.overflow="scroll";a.style.overflowX="hidden";h.style.opacity=.3;d?g.appendChild(a):b.appendChild(a);document.body.appendChild(b);document.body.style.overflow="hidden";h.addEventListener("mousewheel",preventScroll);h.addEventListener("click",this.closePopup);b.addEventListener("click",function(a){c.clickHandler(a);a.preventDefault()});d||a.addEventListener("scroll",function(){c.scrollHandler.call(c,
a)})},iterateOverImages:function(a){a=a.getElementsByTagName("img");for(var d=0,c=a.length;d<c;d++){var b=a[d];this.convertToBase64(b.src,"img-loaded"===b.parentNode.className?b.parentNode.parentNode.href:b.parentNode.href,d,a)}},convertToBase64:function(a,d,c,b){var e=this,f=document.createElement("CANVAS"),h=f.getContext("2d"),g=new Image;g.crossOrigin="Anonymous";g.onload=function(){f.height=g.height;f.width=g.width;h.drawImage(g,0,0);var l={dataURI:f.toDataURL(),src:a,href:d,index:c};e.prepareData.call(e,
l,b);f=null};g.src="http://cors-for-chromell.herokuapp.com/"+a},prepareData:function(a,d){var c=a.dataURI,b=a.src,e=a.index,f=a.href.match(/\.(gif|jpg|png)$/i)[0],f=b.replace(".jpg",f),f=f.replace("dealtwith.it/i/t","endoftheinter.net/i/n"),h=f.match(/\/([^/]*)$/)[1];(h=decodeURIComponent(h))&&f&&c?(this.cacheData[b]={filename:h,fullsize:f,data:c},e===d.length-1&&this.restore(this.updateCache)):console.log("Error while caching image: ","\n",b,h,f,c)},updateCache:function(a){var d=imagemap.cacheData;
if(a.imagemap){for(var c in d)a.imagemap[c]=d[c];a=a.imagemap}else a=d;chrome.storage.local.set({imagemap:a},function(){imagemap.cacheData={}})},restore:function(a){chrome.storage.local.get("imagemap",function(d){d==={}?a(!1):d&&a(d)})},scrollHandler:function(a){var d=this;a.scrollTop>=a.scrollHeight-a.clientHeight-5&&this.currentPage!==this.lastPage&&(this.currentPage++,this.get(function(c){c=d.scrape(c);a.appendChild(c);d.iterateOverImages(c)}))},clickHandler:function(a){if("image_search"!=a.target.id){if("IMG"===
a.target.tagName){var d={};if(a.target.getAttribute("searchresult"))var c=a.target.getAttribute("oldsrc");else var c=a.target.getAttribute("oldsrc")?a.target.getAttribute("oldsrc"):a.target.src,b=/\.(gif|jpg|png)$/i,e=a.target.parentNode.href.match(b),b=c.match(b),c=c.replace(b[0],e[0]);d.quote='<img src="'+c.replace("dealtwith.it/i/t","endoftheinter.net/i/n")+'" />';chrome.runtime.sendMessage(d)}imagemap.closePopup();document.removeEventListener("click",imagemap.clickHandler);a.preventDefault()}},
closePopup:function(){var a=document.getElementById("map_div");a||(a=document.getElementById("search_results"));var d=document.getElementsByClassName("body")[0];a&&document.body.removeChild(a);d.style.opacity=1;document.body.style.overflow="initial";d.removeEventListener("mousewheel",preventScroll)},search:{init:function(){var a=this,d=document.getElementById("image_search").value;/\S/.test(d)?this.lookup(d,function(c,b){document.getElementById("search_results")?((document.getElementById("results_grid")||
document.getElementById("no_results_grid")).remove(),document.getElementById("loading_image").style.display="block"):a.createPopup(b);a.prepareResults(c,b)}):document.getElementById("search_results")&&imagemap.closePopup()},lookup:function(a,d){var c=[];imagemap.restore(function(b){b=b.imagemap;for(var e in b)-1<b[e].filename.indexOf(a)&&c.push(e);d(c,a)})},prepareResults:function(a,d){var c=this;0===a.length?this.formatResults(!1,d):imagemap.restore(function(b){b=b.imagemap;for(var e={},f=0,h=a.length;f<
h;f++){var g=a[f];e[g]=b[g]}c.formatResults(e,d)})},formatResults:function(a,d){if(a){var c=document.createElement("div");c.className="image_grid";c.id="results_grid";c.style.clear="left";for(var b in a){var e=document.createElement("div");e.className="grid_block";var f=document.createElement("img");f.setAttribute("oldsrc",a[b].fullsize);f.setAttribute("searchresult",!0);f.src=a[b].data;e.className="grid_block";e.style.display="inline";e.appendChild(f);c.appendChild(e)}this.updatePopup(c,d)}else this.updatePopup(!1,
d)},createPopup:function(a){var d=document.createElement("div"),c=document.createElement("img"),b=chrome.extension.getURL("/src/images/loading.png");c.id="loading_image";c.style.display="block";c.style.marginLeft="auto";c.style.marginRight="auto";c.style.marginTop="auto";c.style.marginBottom="auto";c.src=b;d.innerHTML='Displaying results for query "<span id="query">'+a+'</span>" :';a=document.createElement("div");var b=window.innerWidth,e=window.innerHeight,f=document.getElementsByClassName("body")[0];
a.id="search_results";a.style.position="fixed";a.style.width=.95*b+"px";a.style.height=.95*e/2+"px";a.style.left=b-.975*b+"px";a.style.top=e-.975*e+"px";a.style.boxShadow="5px 5px 7px black";a.style.borderRadius="6px";a.style.backgroundColor="white";a.style.overFlow="scroll";d.style.color="black";d.style.position="relative";d.style.left="15px";d.style.right="15px";d.style.top="15px";d.style.cssFloat="left";d.style.textAlign="left";d.style.width="100%";d.style.fontSize="16px";d.id="results_header";
a.appendChild(d);a.appendChild(c);document.body.appendChild(a);document.body.style.overflow="hidden";f.addEventListener("mousewheel",preventScroll);f.addEventListener("click",this.closePopup);document.addEventListener("click",imagemap.clickHandler)},updatePopup:function(a,d){document.getElementById("loading_image").style.display="none";document.getElementById("search_results");var c=document.getElementById("results_grid")||document.getElementById("no_results_grid"),b=document.getElementById("results_header"),
e=document.getElementById("query"),f=window.innerWidth,h=window.innerHeight;e.innerHTML!=d&&(e.innerHTML=d);a?(a.style.maxHeight=.95*h/2-51+"px",a.style.maxWidth=.95*f-21+"px",a.style.position="relative",a.style.top="5px",a.style.overflow="scroll",a.style.overflowX="hidden",c&&c.remove(),b.appendChild(a)):(e=document.createElement("div"),f=document.createTextNode("No matches found."),e.id="no_results_grid",e.style.position="relative",e.style.top="5px",e.appendChild(f),c?"no_results_grid"!==c.id&&
(c.remove(),b.appendChild(e)):b.appendChild(e))}}};
