var postMsg={batch_uploader:function(){var a=document.createElement("input");a.type="file";a.multiple=!0;a.value="Batch Upload";a.id="batch_uploads";var c=document.createElement("input");c.type="button";c.value="Batch Upload";c.addEventListener("click",postMsgHelper.startBatchUpload);document.getElementsByTagName("form")[0].insertBefore(a,null);document.getElementsByTagName("form")[0].insertBefore(c,a)},foxlinks_quotes:function(){commonFunctions.foxlinks_quote()},post_before_preview:function(){for(var a,
c,d=document.getElementsByTagName("form")[document.getElementsByTagName("form").length-1].getElementsByTagName("input"),b=0;b<d.length;b++)"preview"==d[b].name&&(c=d[b]),"submit"==d[b].name&&(a=d[b]);a.parentNode.removeChild(a);c.parentNode.insertBefore(a,c)},quick_imagemap:function(){var a=document.getElementsByTagName("input"),a=a[a.length-1],c=document.createElement("button"),d=document.createTextNode(" "),b=document.createElement("input");console.log(a);c.textContent="Browse Imagemap";c.id="quick_image";
b.placeholder="Search Imagemap...";b.id="image_search";a.parentNode.appendChild(d);a.parentNode.appendChild(c);a.parentNode.appendChild(d);a.parentNode.appendChild(b)},create_topic_buttons:function(){if(-1!=document.body.innerHTML.indexOf("Create New Topic")&&!document.getElementById("b")){document.getElementById("message");document.getElementsByTagName("input");var a=document.getElementById("token_desc");a||(a=document.getElementsByTagName("em")[0]);var c=document.createElement("br");a.appendChild(c);
c=document.createElement("input");c.value="Mod";c.name="Mod";c.type="button";c.addEventListener("click",postMsgHelper.qpTagButton,!1);c.id="mod";c.tabIndex=-1;var d=document.createElement("input");d.value="Quote";d.name="Quote";d.type="button";d.addEventListener("click",postMsgHelper.qpTagButton,!1);d.id="quote";d.tabIndex=-1;var b=document.createElement("input");b.value="Spoiler";b.name="Spoiler";b.type="button";b.addEventListener("click",postMsgHelper.qpTagButton,!1);b.id="spoiler";b.tabIndex=-1;
var e=document.createElement("input");e.value="Preformated";e.name="Preformated";e.type="button";e.addEventListener("click",postMsgHelper.qpTagButton,!1);e.id="pre";e.tabIndex=-1;var f=document.createElement("input");f.value="Underline";f.name="Underline";f.type="button";f.addEventListener("click",postMsgHelper.qpTagButton,!1);f.id="u";f.tabIndex=-1;var g=document.createElement("input");g.value="Italic";g.name="Italic";g.type="button";g.addEventListener("click",postMsgHelper.qpTagButton,!1);g.id=
"i";g.tabIndex=-1;var h=document.createElement("input");h.value="Bold";h.name="Bold";h.type="button";h.addEventListener("click",postMsgHelper.qpTagButton,!1);h.id="b";h.tabIndex=-1;a.insertBefore(c,a.nextSibling.lastChild);a.insertBefore(d,c);a.insertBefore(b,d);a.insertBefore(e,b);a.insertBefore(f,e);a.insertBefore(g,f);a.insertBefore(h,g);a.insertBefore(document.createElement("br"),h)}},quickpost_tag_buttons:function(){if(!(-1<document.body.innerHTML.indexOf("Create New Topic"))){var a=document.getElementsByTagName("form")[document.getElementsByTagName("form").length-
1];if(a){document.getElementById("message").focus();var c=document.createElement("input");c.value="Mod";c.name="Mod";c.type="button";c.id="mod";c.addEventListener("click",postMsgHelper.qpTagButton,!1);var d=document.createElement("input");d.value="Quote";d.name="Quote";d.type="button";d.addEventListener("click",postMsgHelper.qpTagButton,!1);d.id="quote";var b=document.createElement("input");b.value="Spoiler";b.name="Spoiler";b.type="button";b.addEventListener("click",postMsgHelper.qpTagButton,!1);
b.id="spoiler";var e=document.createElement("input");e.value="Preformated";e.name="Preformated";e.type="button";e.addEventListener("click",postMsgHelper.qpTagButton,!1);e.id="pre";var f=document.createElement("input");f.value="Underline";f.name="Underline";f.type="button";f.addEventListener("click",postMsgHelper.qpTagButton,!1);f.id="u";var g=document.createElement("input");g.value="Italic";g.name="Italic";g.type="button";g.addEventListener("click",postMsgHelper.qpTagButton,!1);g.id="i";var h=document.createElement("input");
h.value="Bold";h.name="Bold";h.type="button";h.addEventListener("click",postMsgHelper.qpTagButton,!1);h.id="b";a.insertBefore(c,a.getElementsByTagName("textarea")[0]);a.insertBefore(d,c);a.insertBefore(b,d);a.insertBefore(e,b);a.insertBefore(f,e);a.insertBefore(g,f);a.insertBefore(h,g);a.insertBefore(document.createElement("br"),a.getElementsByTagName("textarea")[0])}}},drop_batch_uploader:function(){document.getElementsByTagName("textarea")[0].addEventListener("drop",function(a){a.preventDefault();
document.getElementsByTagName("form")[0].getElementsByTagName("b")[2].innerHTML+=" (Uploading: 1/"+a.dataTransfer.files.length+")";for(var c=0;a.dataTransfer.files[c];c++)commonFunctions.asyncUpload(a.dataTransfer.files[c])})},snippet_listener:function(){var a=document.getElementById("message"),c;a.addEventListener("keydown",function(d){"U+0009"==d.keyIdentifier&&(d.preventDefault(),c=postMsgHelper.findCaret(a),postMsgHelper.snippetHandler(a.value,c))})}},postMsgHelper={create_topic_observer:function(){(new MutationObserver(function(a){for(var c,
d=0,b=a.length;d<b;d++)c=a[d],"token_desc"==c.target.id&&(1<c.addedNodes.length&&"EM"==c.addedNodes[1].tagName&&postMsg.create_topic_buttons(),1<c.removedNodes.length&&"EM"==c.removedNodes[1].tagName&&postMsg.create_topic_buttons(),1<c.addedNodes.length&&"B"==c.addedNodes[1].tagName&&postMsg.create_topic_buttons())})).observe(document,{subtree:!0,characterData:!0,childList:!0,attributes:!0})},findCaret:function(a){var c=0;if(a.selectionStart||"0"==a.selectionStart)c=a.selectionStart;return c},snippetHandler:function(a,
c){var d=a.substring(0,c),b,e,f,g=document.getElementById("message");-1<d.indexOf(" ")?(b=d.split(" "),b=b[b.length-1],-1<b.indexOf("\n")&&(b=b.split("\n"),b=b[b.length-1])):-1<d.indexOf("\n")?(b=d.split("\n"),b=b[b.length-1]):b=d;for(var h in config.snippet_data)h===b&&(e=config.snippet_data[h],f=d.lastIndexOf(b),f=d.substring(0,f),a=a.replace(d,f+e),g.value=a,e=a.lastIndexOf(e)+e.length,g.setSelectionRange(e,e))},startBatchUpload:function(a){a=document.getElementById("batch_uploads");if(0==a.files.length)alert('Select files and then click "Batch Upload"');
else{document.getElementsByTagName("form")[0].getElementsByTagName("b")[2].innerHTML+=" (Uploading: 1/"+a.files.length+")";for(var c=0;a.files[c];c++)commonFunctions.asyncUpload(a.files[c])}},qpTagButton:function(a){if("INPUT"!=a.target.tagName)return 0;var c=a.target.id,d=/\*/m,b=document.getElementById("message"),e=b.scrollTop,f=b.value.substring(0,b.selectionStart),g=b.value.substring(b.selectionEnd,b.value.length),h=b.value.substring(b.selectionStart,b.selectionEnd);b.selectionStart==b.selectionEnd?
(d.test(a.target.value)?(a.target.value=a.target.name,a=b.selectionStart+c.length+3,b.value=f+"</"+c+">"+g):(a.target.value=a.target.name+"*",a=b.selectionStart+c.length+2,b.value=f+"<"+c+">"+g),b.selectionStart=a):(a=b.selectionStart+2*c.length+h.length+5,b.value=f+"<"+c+">"+h+"</"+c+">"+g,b.selectionStart=f.length);b.selectionEnd=a;b.scrollTop=e;b.focus()},imagemapDebouncer:"",imagemapHelper:function(){var a=document.styleSheets[0];a.insertRule("#loading_image { -webkit-animation:spin 2s linear infinite; }",
1);a.insertRule("@-webkit-keyframes spin { 100% { -webkit-transform:rotate(360deg); } }",1);document.getElementById("quick_image").addEventListener("click",function(a){imagemap.init();a.preventDefault()});document.getElementById("image_search").addEventListener("keyup",function(){clearTimeout(postMsgHelper.imagemapDebouncer);this.imagemapDebouncer=setTimeout(function(){imagemap.search.init.call(imagemap.search)},250)})},init:function(){chrome.runtime.sendMessage({need:"config"},function(a){config=
a.data;a="";window.location.href.match("boards")||(a="_pm");for(var c in postMsg)if(config[c+a])try{postMsg[c]()}catch(d){console.log("error in "+c+":",d)}config.create_topic_buttons&&postMsgHelper.create_topic_observer();config.quick_imagemap&&postMsgHelper.imagemapHelper()})}};postMsgHelper.init();
