var topicList={ignore:{users:[],keywords:[]},highlight:{keywords:{},tags:{}},config:{},ignorated:{total_ignored:0,data:{users:{},keywords:{}}},index:1,pm:"",functions:{ignorator_topiclist:function(c,a){var b=topicList.ignore.users;if(b)for(var d=c.getElementsByTagName("td")[1],e=0,f=b.length;e<f&&d&&!(-1<d.innerHTML.indexOf("<td>Human</td>"));e++)d.getElementsByTagName("a"),d.getElementsByTagName("a")[0]&&d.getElementsByTagName("a")[0].innerHTML.toLowerCase()==b[e]&&(topicList.config.debug&&console.log('found topic to remove: "'+
c.getElementsByTagName("td")[0].getElementsByTagName("a")[0].innerHTML.toLowerCase()+'" author: '+b[e]+" topic: "+a),c.setAttribute("ignored",!0),c.style.display="none",topicList.ignorated.total_ignored++,topicList.ignorated.data.users[b[e]]?(topicList.ignorated.data.users[b[e]].total++,topicList.ignorated.data.users[b[e]].trs.push(a)):(topicList.ignorated.data.users[b[e]]={},topicList.ignorated.data.users[b[e]].total=1,topicList.ignorated.data.users[b[e]].trs=[a]))},ignore_keyword:function(c,a){if(topicList.config.ignore_keyword_list){var b=
topicList.ignore.keywords,d,e=!1;if(c.getElementsByTagName("td")[0]){d=c.getElementsByTagName("td")[0];username=d.getElementsByTagName("a")[0].innerHTML;for(var f=0,h=b.length;f<h;f++)if(e=-1!=username.toLowerCase().indexOf(b[f].toLowerCase()))topicList.config.debug&&console.log('found topic to remove: "'+c.getElementsByTagName("td")[0].getElementsByTagName("a")[0].innerHTML.toLowerCase()+'" keyword: '+b[f]+" topic: "+a),d.parentNode.style.display="none",topicList.ignorated.total_ignored++,topicList.ignorated.data.keywords[b[f]]?
(topicList.ignorated.data.keywords[b[f]].total++,topicList.ignorated.data.keywords[b[f]].trs.push(a)):(topicList.ignorated.data.keywords[b[f]]={},topicList.ignorated.data.keywords[b[f]].total=1,topicList.ignorated.data.keywords[b[f]].trs=[a])}}},page_jump_buttons:function(c,a){var b;if(-1<window.location.href.indexOf("inbox.php")){if(!topicList.config.page_jump_buttons_pm)return;b=!0}var d,e=c.getElementsByTagName("td")[0];if(e){d=document.createElement("span");b&&(d.style.cssFloat="right");try{e.getElementsByTagName("a");
var f=document.createTextNode(" "),h=document.createElement("a");h.href="##"+a;h.id="jumpWindow";h.innerHTML="#";var g=document.createElement("a");g.href="##"+a;g.id="jumpLast";g.innerHTML="&gt;";d.appendChild(h);d.appendChild(f);d.appendChild(g);b?e.appendChild(d):e.getElementsByClassName("fr")[0].appendChild(d)}catch(k){topicList.config.debug&&console.log("locked topic?"),b=e.getElementsByTagName("span")[0].getElementsByTagName("a"),b=b[0].href.match(/(topic|thread)=([0-9]+)/)[2],d.innerHTML='<a href="##'+
b+'" id="jumpWindow">#</a> <a href="##'+b+'" id="jumpLast">&gt;</a>',e.getElementsByClassName("fr")[0].insertBefore(d,null)}}},enable_keyword_highlight:function(c){var a,b=topicList.highlight.keywords;if(b){a=c.getElementsByTagName("td")[0].getElementsByClassName("fl")[0].getElementsByTagName("a")[0].innerHTML;for(var d=0;b[d];d++)for(var e=0;b[d].match[e];e++){if("/"==b[d].match[e].substring(0,1))var f=new RegExp(b[d].match[e].substring(1,b[d].match[e].lastIndexOf("/")),b[d].match[e].substring(b[d].match[e].lastIndexOf("/")+
1,b[d].match[e].length)),h=a.match(f);else var f=b[d].match[e].toLowerCase(),h=-1!=a.toLowerCase().indexOf(f);if(h){var g=c.getElementsByTagName("td")[0],h=g.getElementsByTagName("a");g.setAttribute("highlighted",!0);g.style.background="#"+b[d].bg;g.style.color="#"+b[d].color;for(var g=0,k=h.length;g<k;g++)h[g].style.color="#"+b[d].color;topicList.config.debug&&console.log("highlight topic "+a+" keyword "+f)}}}},enable_tag_highlight:function(c){var a=topicList.highlight.tags;if(a)for(var b=c.getElementsByTagName("td")[0].getElementsByClassName("fr")[0].getElementsByTagName("a"),
d=0,e=b.length;d<e;d++){tagToCheck=b[d];for(var f=0;a[f];f++)for(var h=0;a[f].match[h];h++){var g=a[f].match[h];if(tagToCheck.innerHTML.toLowerCase().match(g)){var k=c.getElementsByTagName("td")[0],g=k.getElementsByTagName("a");k.setAttribute("highlighted",!0);k.style.background="#"+a[f].bg;k.style.color="#"+a[f].color;for(var k=0,l=g.length;k<l;k++)nodeAnchor=g[k],nodeAnchor.style.color="#"+a[f].color;topicList.config.debug&&console.log("highlight topic "+c+" tag "+a[f].match[h])}}}},userhl_topiclist:function(c){if(topicList.config.enable_user_highlight){var a,
b=topicList.config.user_highlight_data;if(c.getElementsByTagName("td")[1].getElementsByTagName("a")[0]&&(a=c.getElementsByTagName("td")[1].getElementsByTagName("a")[0].innerHTML.toLowerCase(),b[a])){topicList.config.debug&&console.log("highlighting topic by "+a);c.setAttribute("highlighted",!0);c=c.getElementsByTagName("td");for(var d=0,e=c.length;d<e;d++){var f=c[d];f.setAttribute("highlighted",!0);var h=f.getElementsByTagName("a");f.style.background="#"+b[a].bg;f.style.color="#"+b[a].color;for(var f=
0,g=h.length;f<g;f++){var k=h[f];k.setAttribute("highlighted",!0);k.style.color="#"+b[a].color}}}}},zebra_tables:function(c,a){if(0===a%2)for(var b=0;c.getElementsByTagName("td")[b];b++)""===c.getElementsByTagName("td")[b].style.background&&(c.getElementsByTagName("td")[b].style.background="#"+topicList.config.zebra_tables_color)}},prepareArrays:function(){if(this.config.ignorator_list)if(-1==this.config.ignorator_list.indexOf(","))this.ignore.users[0]=this.config.ignorator_list.toLowerCase();else for(var c=
this.config.ignorator_list.split(","),a=0,b=c.length;a<b;a++)this.ignore.users[a]=c[a].toLowerCase().trim();if(this.config.ignore_keyword_list)if(-1==this.config.ignore_keyword_list.indexOf(","))this.ignore.keywords[0]=this.config.ignore_keyword_list;else for(c=this.config.ignore_keyword_list.split(","),a=0,b=c.length;a<b;a++)this.ignore.keywords[a]=c[a].toLowerCase().trim();for(a=0;this.config.keyword_highlight_data[a];a++)this.highlight.keywords[a]={},this.highlight.keywords[a].bg=this.config.keyword_highlight_data[a].bg,
this.highlight.keywords[a].color=this.config.keyword_highlight_data[a].color,this.highlight.keywords[a].match=this.config.keyword_highlight_data[a].match.split(",");for(a=0;this.config.tag_highlight_data[a];a++)this.highlight.tags[a]={},this.highlight.tags[a].bg=this.config.tag_highlight_data[a].bg,this.highlight.tags[a].color=this.config.tag_highlight_data[a].color,this.highlight.tags[a].match=this.config.tag_highlight_data[a].match.split(",")},checkTags:function(){for(var c=document.getElementById("bookmarks").getElementsByTagName("span"),
a={},b,d,e=0,f=c.length;e<f;e++)c[e].className||(d=c[e].getElementsByTagName("a")[0].innerHTML,b=c[e].getElementsByTagName("a")[0].href.match("/topics/(.*)$")[1],a[d]=b);chrome.runtime.sendMessage({need:"save",name:"saved_tags",data:a})},addListeners:function(){document.addEventListener("click",function(c){if(c.target.id.match(/(jump)([Last|Window])/)){c.preventDefault();var a=topicList.handle.pageJump(c);0!==a&&(1==c.which?window.location.href=a:2==c.which&&window.open(a))}})},handle:{message:function(c){if("ignorator_update"!==
c.action)switch(c.action){case "showIgnorated":c=document.querySelectorAll("[ignored]");for(var a=0,b=c.length;a<b;a++)c[a].style.display="",c[a].style.opacity=".7";break;default:this.config.debug&&console.log("invalid action",c)}},pageJump:function(c){var a,b,d;-1<window.location.href.indexOf("history.php")?(b=!0,a=c.target.parentNode.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("td")[2]):-1<window.location.href.indexOf("inbox.php")?(d=!0,a=c.target.parentNode.parentNode.nextSibling.nextSibling):
a=c.target.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("td")[2];a=Math.ceil(a.innerHTML.split("<")[0]/50);if("jumpWindow"==c.target.id){if(pg=prompt("Page Number ("+a+" total)","Page"),void 0==pg||"Page"==pg)return 0}else pg=a;return b?c.target.parentNode.parentNode.parentNode.getElementsByTagName("a")[0].href+"&page="+pg:d?c.target.parentNode.parentNode.firstChild.href+"&page="+pg:c.target.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("td")[0].getElementsByTagName("a")[0].href+
"&page="+pg}},callFunctions:function(c){for(var a=document.getElementsByClassName("grid"),b=this.functions,d=this.config,e=0,f=a.length;e<f;e++)for(var h=a[e].getElementsByTagName("tr"),g=1,k=h.length;g<k;g++){var l=h[g];if(!l.innerText||"See More"!=l.innerText)for(var m in b)if(d[m+c])b[m](l,g)}this.config.dramalinks&&!window.location.href.match(/[inbox|main].php/)&&(c=document.getElementsByTagName("h1")[0],dramalinks.appendTo(c));this.config["page_jump_buttons"+this.pm]&&this.addListeners();try{topicList.checkTags()}catch(n){console.log("Error finding tags")}this.config.hide_ignorator_badge||
this.globalPort.postMessage({action:"ignorator_update",ignorator:this.ignorated,scope:"topicList"})},init:function(c){this.config=c.data;this.prepareArrays();this.globalPort=chrome.runtime.connect();this.globalPort.onMessage.addListener(this.handle.message);window.location.href.match(/topics/)?this.config.dramalinks&&chrome.runtime.sendMessage({need:"dramalinks"},function(a){dramalinks.html=a.data;dramalinks.config=topicList.config}):window.location.href.match(/inbox.php/)&&(this.pm="_pm");"loading"==
document.readyState?document.addEventListener("DOMContentLoaded",function(){topicList.callFunctions(topicList.pm)}):this.callFunctions(this.pm)}};chrome.runtime.sendMessage({need:"config"},function(c){topicList.init.call(topicList,c)});
